import "./globals.css";
import { Providers } from "./providers";
import Header from "@/components/Header/Header";
import { roboto_condensed } from "./fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Providers>
        <html lang="en">
          <body className={roboto_condensed.className}>
            <Header />

            {children}
          </body>
        </html>
      </Providers>
    </>
  );
}
